---
- name: Update all packages, deploy SSH Keys to Managed Nodes, Install Python, Add a new User, Install Webserver, Install Docker and Create Container
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update all packages
      apt:
       upgrade: dist
   
  roles:
    - deploy_ssh_keys
    - python
    - add_user
    - webserver
    - docker
