---
# Role add_user

- src: https://github.com/canerto/ansible-role-add_user
  scm: git
  version: master
  name: ansible-role-add_user
#- src: https://github.com/canerto/pp-ba-ansible/roles/deploy_ssh_keys
#- src: https://github.com/canerto/pp-ba-ansible/roles/docker
#- src: https://github.com/canerto/pp-ba-ansible/roles/lamp
#- src: https://github.com/canerto/pp-ba-ansible/roles/python
#  scm: git
#  version: master
#  name: roles