---

# Repo Variables
docker_apt_release_channel: stable            # You can also use 'edge', 'nightly' or 'test'
docker_apt_arch: amd64                        # You can change to 'armhf', 'arm64',... if needed
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# A list of users who will be added to the docker group
docker_users:
- itsadmin
- user1
- user2
- user3